### ISSUE TITLE
Separate vita homebrews from games

### ISSUE THREAD

**Issue by kenshin088** [ONElua/ONEMenu-for-PSVita#10]
It would be better for quickly finding the game to launch if you grouped the homebrews in separate section like for psx games

**Comment by ONElua** [comment]
Yes...
and psp games&ps1 games a same category...

**Comment by szpieg-z-krainy-deszczowcow** [comment]
Why PSP & PSX games in one category as they are different content? Well, technically the are not but from a user perspective they are different things. ;)
