### ISSUE TITLE
Vertical scrolling option

### ISSUE THREAD

**Issue by kenshin088** [ONElua/ONEMenu-for-PSVita#11]
Option for vertical scrolling for faster/better navigation. It would resemble PS4 UI. You could possibly fit 2-3 rows of vita games per screen.

**Comment by ONElua** [comment]
Then it would not be onemenu ...

**Comment by kenshin088** [comment]
I'm not sure what you mean that it wont be onemenu? Is it really a big deal if there is vertical scrolling instead of horizontal? Just curious. thanks.
