### ISSUE TITLE
Pin favorites apps/games to the top

### ISSUE THREAD

**Issue by kenshin088** [ONElua/ONEMenu-for-PSVita#15]
Would be really awesome if we could pin favorite games to the beginning of the list. Another option would be to create a whole new category (like you have for apps, psx and hopefully one for homebrews) that shows only your favorite games, apps, homebrews, etc. This way when you open onemenu it goes right to your favorites section.

I've posted a lot of possible enhancements because i see a lot of potential in this app to replace the standard vita homescreen. I use the autoBoot plugin to directly launch onemenu so we're one step closer to replacing the default launcher. Keep up the great work.

**Comment by ONElua** [comment]
There really are many requests...
Thanks for all your ideas.
I have to see what are possible to do

**Comment by ONElua** [comment]
please...
Send me DM in twitter
i need tester...

**Comment by kenshin088** [comment]
I sent a message on twitter. @DaRealKenshin
