### ISSUE TITLE
Missing text colour variables for themes.

### ISSUE THREAD

**Issue by szpieg-z-krainy-deszczowcow** [ONElua/ONEMenu-for-PSVita#21]
There are colours which cannot be skinned like i.e number of files in dir in right corner, vertical scrollbar etc. Also I found that some variables are common across different menus (bad designed IMHO as some conflicting). I'm based on last release and default screen.

Due to above, I cannot make good looking skin. ;p

**Comment by ONElua** [comment]
Honestly, giving each text its own color on the ini file could be complicated to keep track on which is each, but if you think thats a good idea, please send me some screenshots of the modified bar or text (missings)...
with that maybe we can acomplish something better
