### ISSUE TITLE
Long black loading screen when no/slow internet

### ISSUE THREAD

**Issue by kenshin088** [ONElua/ONEMenu-for-PSVita#22]
If I load the app while my internet connection is down or very slow I get a black loading screen that just hangs for a very long time. I think this happens when there is an update to the app and there is no internet connection it tries to reach the server but ends up hanging for a very long time instead. It probably shows the black screen for about 30 to 40 seconds before the app actually starts scanning all the games and homebrews.

**Comment by ONElua** [comment]
In this case...
we can make the internet signal must be at least 55 to enter the update
