### ISSUE TITLE
Constantly Crashes

### ISSUE THREAD

**Issue by ilikemyrealname** [ONElua/ONEMenu-for-PSVita#27]
Updated to 2.01 (latest atm), getting constant crashes. Can’t be in the app for more than a few seconds without it completely halting. All buttons don’t work, except the power button. I can lock the screen but then it unlocks to its halted state. Can’t bring up any Menus or get to live area. I have to hold power button until PS button starts to blink, then hold again for 30 seconds to enter PS menu that allows me to restart system. I’ve tried uninstalling and re-installing, same exact issues. One thing to note is I have the 200gb card and it is full, minus 10gb or so. I’m wondering if the app is struggling/crashing because of so many games on my system? Lastly, I have just let the app sit for like 10-20 minutes, but it never became responsive again.

Lmk if there is any other info I can provide to further help the cause.

**Comment by ONElua** [comment]
yes...please try with v1.01

**Comment by ONElua** [comment]
PD: Please try...
https://www.dropbox.com/s/6658zxszvfx4nnd/ONEMenuVita_TEST.vpk?dl=0

**Comment by ilikemyrealname** [comment]
Yup, v1.01 has worked very well in the past.

Tried your DB link and it works.

I'm no dev but it seems like a merge of v1's way of handling the list of games and v2's way of displaying them (ie, separating Vita games and homebrew).

Really nice work! Looking forward to watching this develop even further. 

Thank you for your reply.

**Comment by ONElua** [comment]
The main difference between v1.xx and v2.xx is the way the icons are loaded, this is done on an independent thread thats why starts off faster cause the icons list gets updated when the icons need to be shown
so, the thread for loading the icons is what causes the crash

**Comment by ilikemyrealname** [comment]
Well, if there’s anything I can do to help out, let me know. I have this Vita with a huge library and am willing to test releases if that would be of any help. 

Thanks again for everything.

**Comment by ONElua** [comment]
ok..send me DM in twitter
