### ISSUE TITLE
Non Alphabet lang file support

### ISSUE THREAD

**Issue by azumukupoe** [ONElua/ONEMenu-for-PSVita#3]

**Comment by ONElua** [comment]
which alphabet?

**Comment by azumukupoe** [comment]
@ONElua
I would like to translate your apps into Japanese.

**Comment by ONElua** [comment]
JAPANESE.TXT

**Comment by azumukupoe** [comment]
@ONElua
japanese characters get garbled as it does with your ABM

**Comment by ONElua** [comment]
but im fix in this eboot.bin..please try

**Comment by ONElua** [comment]
sendme screenshot please...
