### ISSUE TITLE
Modify favorites 

### ISSUE THREAD

**Issue by kenshin088** [ONElua/ONEMenu-for-PSVita#30]
Two suggestions for improving favorites

1) Separate favorites into it's own category do that you can switch between favorites, games, home brews, psx/psp category easily. Having it separate is inefficient because we need to dig through settings to activate/disable. 

2) If #1 is not doable, another suggestion is, when someone favorites a game, move that game to the front of the list. Therefore you will see it first in that category. Any additional games added to favorites will appear BEFORE the previously added game.

**Comment by ONElua** [comment]
done!!! 
option 1.
