### ISSUE TITLE
Language text invalid in Vision 2.02

### ISSUE THREAD

**Issue by gnatydnac** [ONElua/ONEMenu-for-PSVita#38]
My psvita system lang is Chinese Traditional, the chinese_t works fine in 1menu v2.01 but invalid in v2.02(shows back to the default english), until I renamed the file “chinese_t.txt” to “english_us.txt”. Maybe somgthing wrong with the System Lang recognition. plz fix this bug. thx

**Comment by ONElua** [comment]
Update your translation...
PD: https://github.com/ONElua/ONEMenu-for-PSVita/commit/d94d94c428d99520a0b32668882e0461b61e8038#diff-917ff9b070871448df2adc26c8e99710

**Comment by ONElua** [comment]
please send me your translation :D

**Comment by gnatydnac** [comment]
I've uploaded on google drive(https://drive.google.com/file/d/1VB9s9zxWO3d6n5TnMPsUT_C1j8p8YiL3/view?usp=sharing).

**Comment by gnatydnac** [comment]
The Translation has no problem becuz both the 2.00 and 2.02 text run ok on the 1menu v2.01

**Comment by gnatydnac** [comment]
PS: this is a simplified CN text and I do name it "chinese_s.txt", but we all set the sys lang as CN_T, because of the game region(some game shows CN_T only when the sys lang is CN_T,sadly there're almost no CN_S game).  So I think It's better to set the Lang manually XD.

**Comment by ONElua** [comment]
your try with UTF-8 without BOOM ??

**Comment by gnatydnac** [comment]
Of course...I mean the same translation work fine on v2.01 but invalid on v2.02. so what's the correct format?

**Comment by gnatydnac** [comment]
almost forget the simplified CN font: https://drive.google.com/open?id=1uFpoAsuHAvlYSBe2uqhTKIgSpXCD9sCN
CN char won't display whitout this.

**Comment by ONElua** [comment]
ok...send me DM in twitter...

**Comment by ONElua** [comment]
or 
gdljjrod@gmail.com

**Comment by ONElua** [comment]
please...replace utils.lua
https://www.dropbox.com/s/jt4vr2ve0tynr6o/utils.zip?dl=0
and send me screenshot of the first os.message

**Comment by gnatydnac** [comment]
sent
