### ISSUE TITLE
Launching ONEMenu fails

### ISSUE THREAD

**Issue by frep** [ONElua/ONEMenu-for-PSVita#40]
After starting ONEMenu for PSVita (v2.03), "one debugger" appears:
file: ux0:/app/1MENUVITA/system/advanced.lua
line: 96
error: attempt to concatenate field 'pgf' (a nil value)

Please let me know, if more information are needed to locate the problem.

**Comment by ONElua** [comment]
Update ...your Translation...
take the english_us.txt from system/lang/
EDIT:
Please re-download https://github.com/ONElua/ONEMenu-for-PSVita/blob/master/ONEMenuVita/system/lang/english_us.txt#L181
and put ux0:data/ONEMENU/lang/english_us.txt

**Comment by frep** [comment]
Thank you for your quick response.

There was no difference between the actual file and the re-downloaded one. However, I still replaced the file, but the result was the same.

But since you pointed me to the language files, I changed the system language to english_us (was german before) and the app worked like a charm!

Thanks again for your work.

**Comment by ONElua** [comment]
ok
my error
https://github.com/ONElua/ONEMenu-for-PSVita/blob/master/ONEMenuVita/system/lang/german.txt#L181

EDIT: Please re-download german.txt

**Comment by frep** [comment]
With the new german.txt, the app also works with system language german.
Thanks for the correction!

**Comment by ONElua** [comment]
:D
