### ISSUE TITLE
PS_TV and adrenaline 

### ISSUE THREAD

**Issue by ToniHC** [ONElua/ONEMenu-for-PSVita#44]
Hello,

I'm user of PS_TV with sd2vita and I 'cant launch adrenaline 6,61 from ONEMenu. I don't know if a vita users have same problem. The app don't load, I must reset my pstv for can launch again from original dash. 

Best

Toni.

**Comment by ONElua** [comment]
what kind of error do you get? error code? black screen? freezes?
did you add the corresponding adrenaline line at ur0:tai/config.txt?

**Comment by ToniHC** [comment]
Well I done a two quick videos for you can see it. Maybe is error from my pstv, no idea for this reason I'm asking.

If I load ONEMenu and launch adrenaline not work for me...

https://youtu.be/ZYtwIH9G3oo

But If I load first Adrenaline and later I launch it from ONEMenu works. 

https://youtu.be/J0jm3o1Spso

I love your dash for a pstv it's perfect for it and I want setup by default at boot, but I have this issue with adrenaline. 

Thanks!

**Comment by ONElua** [comment]
Please add in your ur0:tai/config.txt
*KERNEL
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
reboot your psvita ...

https://github.com/TheOfficialFloW/Adrenaline#how-to-install

**Comment by ToniHC** [comment]
thank you so much! this worked perfect. 

Keep the good work! 

Cheers!
