### ISSUE TITLE
Sort Titles

### ISSUE THREAD

**Issue by lovelydumpling** [ONElua/ONEMenu-for-PSVita#45]
I notice that this wonderful app sorts Adrenaline Bubbles alphabetically, which I _absolutely_ adore. But for homebrew and games, they seem to be sorted by folder ID? Is there any way to sort them alphabetically by title?

EDIT:
To keep from opening too many threads
I'm also wondering if adding music to theme customization might ever be feasible?

**Comment by ONElua** [comment]
edit with notepad++
https://github.com/ONElua/ONEMenu-for-PSVita/blob/master/ONEMenuVita/system/appman.lua#L88
table.sort(list, function (a,b) return string.lower(a.id)<string.lower(b.id) end)
for
table.sort(list, function (a,b) return string.lower(a.title)<string.lower(b.title) end)

**Comment by ONElua** [comment]
I think before many asked that the games vita be sorting by id, for the question of the region of the games.

**Comment by lovelydumpling** [comment]
ooooh ok! Yeah I can do that, thank you! And I suppose that makes sense... at least for when people have multiple regions of the same title.

Should I open a new thread about the music thing or just kinda drop it?
<- doesn't know github ettiquette

**Comment by ONElua** [comment]
The sound module is delicate, try to replace it with short sounds in .ogg in systme/theme/default but if they are not compatible it will cause crashs.
Im working Option Sort: Title/id
you can download all the repo and replace all the files... and try
https://github.com/ONElua/ONEMenu-for-PSVita/tree/91341865d64b26979fc8fa732cd7166f3cb97e29

**Comment by itylermartin** [comment]
> edit with notepad++
> https://github.com/ONElua/ONEMenu-for-PSVita/blob/master/ONEMenuVita/system/appman.lua#L88
> table.sort(list, function (a,b) return string.lower(a.id)<string.lower(b.id) end)
> for
> table.sort(list, function (a,b) return string.lower(a.title)<string.lower(b.title) end)

This isn't Working For Me. Do We Also Edit the Next Line Containing "(a.id)>string"
