### ISSUE TITLE
Background Music for OneMenu

### ISSUE THREAD

**Issue by silverizer** [ONElua/ONEMenu-for-PSVita#46]
Hi Onelua,

Im a fan of your works I just wonder if there is a way you can add background music for ONEMenu app
I would really appreciate your response
Thanks

**Comment by DavisDev** [comment]
Hello @silverizer!
Yes, we can add it, but ... we do not have a good bgm music,
If you have or know, one free license or with the consent of the author, we add it immediately!

Regards!
P.S. ONElua is the name of the team of programmers and graphic designers.

**Comment by silverizer** [comment]
​How about this one?


https://www.youtube.com/watch?v=-9Z5Nhsm7GA



 Malik Bash.mp3
<https://drive.google.com/file/d/1oH50au2_DCPdT_FNxugopfTeqofhP7v1/view?usp=drive_web>
​​
 Malik-Bash.at9
<https://drive.google.com/file/d/1fbFIP_tOASWo9HZF-Dux5yF-HqclbU3o/view?usp=drive_web>
​

**Comment by DavisDev** [comment]
Excellent @silverizer , Thanks, it seems fine, then we pass you a test, and you tell us what you think,

**Comment by silverizer** [comment]
Ok Great. I look forward to hearing from you.

**Comment by silverizer** [comment]
or you may also try this one since you already have a PS4 theme

https://drive.google.com/file/d/1xsHdKT7-SrHTmEzX29jWD7l1aeSrPYQD/view?usp=sharing
