### ISSUE TITLE
Request: Edit existing bubble name with/without app.db modification

### ISSUE THREAD

**Issue by TheRadziu** [ONElua/ONEMenu-for-PSVita#48]
Hey, Due to new 'rip' feature I got interested in your homebrew and I'm really impressed by it so far, but I've got some suggestions:

~~1. Rename "Rip Game" to something else like "Clean-Up Game Files" / "Slim Down Game size" / "Reduce Game Size" (probably the last one would be best, its up to you). "Rip Game" suggest ripping game files [like for making NoNpDRM copy of a game].~~
~~2. System message that is being displayed IF there are no duplicate files present during "Rip game" file check is in (probably) spanish "Ningun archivo duplicando". Shouldn't it be in English?~~
3. Add new feature(or more like shortcut) under /\ game options - > Edit param.sfo/ Edit Bubble. This file is PFS encrypted so you'll need to use VitaShell's code to edit this file under PFS encryption later (so it'll stay encrypted after edits are saved)
`ux0:/appmeta/GAMEID/param.sfo` ~~forgot to mention which file im referring to, lol~~
4. On finished param.sfo / bubble edits prompt user if he/she wants to update DB with Yes/No question. This is needed for vita to recognize param.sfo changes user made to the bubble. 

edit:
 Ad1 and Ad2 - Made pull request that would fix  those https://github.com/ONElua/ONEMenu-for-PSVita/pull/49

**Comment by ONElua** [comment]
Thks for Ad1 and Ad2
Let me fix a bug I have about the SFO edition and I'll take your ideas

**Comment by TheRadziu** [comment]
Ad3 - Forgot to say I'm talking about `ux0:/appmeta/GAMEID/param.sfo`. Seems like after game is promoted(bubble created) `/app/GAMEID/sce_sys/param.sfo` or `/patch/GAMEID/sce_sys/param.sfo` is no longer used during db update/refresh and appmeta is used instead. This is just a theory in process so you might need to research it a bit further. I cant do it rn cos my vita is not really functional for next few days

Another way, but less permanent (edits are lost after db update/refresh/rebuild) might be direct app.db edits (which I was usually doing to translate bubbles up to this point) but I'd rather have more permanent appmeta method of doing that via OneMenu

**Comment by ONElua** [comment]
What fields need to be modified on the param.sfo??
Cause I have a bug when modifying the field PSP2_SYSTEM_VER

**Comment by TheRadziu** [comment]
I'd like it to be able to edit at least bubble's name.

**EDIT: 25.05.18 - the bare minimum are stitle and title fields**

**Comment by ONElua** [comment]
OK
In a few days I sent you a test.

**Comment by ONElua** [comment]
When using the option OpenDecrypted, I tranfered the SFO via ftp to my pc and modified it, but when trying to transfer it back to the vita the ftp gives me an error, so, something else has to be done so the file gets the right encryption to work properly.
And if I do it directly with ONEMenu the sfo takes the changes but the app/game will not refresh

**Comment by TheRadziu** [comment]
For now, you can implement temporary Bubble name edit via `ur0:/shell/db/app.db` but keep in mind this change will be lost (name will be reverted to original one) after DB refresh (for example when you're swapping microsd/vita mem cards). 

I fixed my vita so I'll try to research how to make it permanent without the need to reinstall the game with modified param.sfo. Will report back what I discover.

**Comment by TheRadziu** [comment]
Okay, done some testing myself and I was right, here is full write-up on the process right now & how it should work on OneMenu:

The current process to permanently rename the bubble / make changes to it is:
1. Using latest (1.9) Vitashell go to `ux0:/appmeta/` and using Open Decrypted open GAMEID directory of the desired game, then start FTP server,
2. On PC connect to the vita, navigate to the `ux0:/appmeta/GAMEID/` and download `param.sfo`
3. Make changes to it, preferably SFOEditor by leecherman,
4. While still being connected to open decrypted vita gameid directory, upload edited param.sfo back

Now there are two ways you can go:

5a. Make same changes to `ur0:/shell/db/app.db` << This will ONLY require you to reboot vita once and you're set [This way is quicker, since reboot doesnt take as much time as db update, but I can imagine it will require more code to be written to implement] 
5b. Trigger database update (not rebuild!), for example using OneMenu OR swapping memory card twice (Current card(1) -> different card(2) -> current card(1)) [This way is easier to code since you already have such function in your app]

Pros:
-You don't have to reinstall the game to modify bubble/param.sfo,
-Changes will carry between DB updates and memory card swaps, making this modification permanent.

Cons: 
-ONE reboot is needed (5th step) for vita to utilize the change,
-This will modification will be lost on game update through livearea, but there is no way to avoid that,

Unknown (not yet tested):
-IDK if edit will carry on the full DB rebuild since I'm not sure if it will use `/app/` and `/patch/` param.sfo or it will use `/appmeta/` just like DB rebuild,

---

Now how I imagine OneMenu to work:
1. Under Game's /\ Menu Add "edit bubble" feature
2. This, under PFS layer, will give you full param.sfo editor (just like it does right now for decrypted param.sfo files in /app and /patch [steps 1-4, you can check vitashell's code to get the idea how he does it in his homebrew or if you just want to use vitashell's kernel instead check this -> https://github.com/dots-tb/rePatch-reDux0/blob/master/rePatchAIDs/main.c#L182 ]
3. After change file is saved under PFS layer, encrypting modified file back
4. Now OneMenu will prompt user if he wants to reboot to apply changes he made (and this will do either step 5a or step 5b, its up to you @ONElua

**Comment by ONElua** [comment]
I found something with the pfs folder, this option will be totally discarded :/

sce_pfs/pflist
It contains the sha256 of each file and although I have modified it, it does not allow to do the reinstallation
![2018-05-24-202439](https://user-images.githubusercontent.com/25811032/40549479-2ac97b94-5ffd-11e8-84f3-aeb0de42ebeb.png)
![sfo](https://user-images.githubusercontent.com/25811032/40549480-2ae40180-5ffd-11e8-90e5-715426fa7318.png)

**Comment by TheRadziu** [comment]
You're looking into `/app/` which is not used or mentioned in the permanent method I've described [for existing bubbles]

Vita takes param.sfo values from `ux0:/appmeta/` on database refresh, app and patch are ignored. 

~~about decrypted param.sfo in `/app/` and `/patch/` I've modified them many times on nonpdrm/retail games and it always worked just fine (one catch is you need to have modified param.sfo **BEFORE** 'installing' the game via refresh livearea for the first time (so before having a bubble for that title), thats why I'm telling you how to utilize appmeta instead in order to edit existing bubbles)~~ That worked on 3.60, it doesnt on 3.65, but it really doesnt matter since my feature request & writeup is about modifying EXISTING bubbles
**completely ignore file you found, its not created or used by vita, but I know now how/from where you downloaded your game :)** 

If you're still having issues recreating what I did, you can either join this discord server: https://discord.gg/6Udcx2w or DM me on discord directly: Radziu#9094, so I could help you with that OR just send you modified encrypted param.sfo so you'll see the final result on your own vita
