### ISSUE TITLE
More lines should be editable to rename bubbles

### ISSUE THREAD

**Issue by octopuserectus** [ONElua/ONEMenu-for-PSVita#52]
Some games like PSCE00567, PCSE00277, PCSE00683 and so on have "(S)TITLE_XX" (e.g. (S)TITLE-00, (S)TITLE-01, and so on) entries which ONEMenu does not allow to edit. Just changing the TITLE and STITLE does nothing, the name stays the same.

**Comment by ONElua** [comment]
ok.

**Comment by ONElua** [comment]
I can solve the STITLE ...
This really is the one that matters, since it is shown in the LiveArea
TITLE leave it alone for games without TITLE_XX

![sin titulo](https://user-images.githubusercontent.com/25811032/40941054-4b9bf8e6-680f-11e8-9de6-5984b0cf2883.png)
