### ISSUE TITLE
QR DownLoader may or may not be broken

### ISSUE THREAD

**Issue by shinobuwu** [ONElua/ONEMenu-for-PSVita#54]
When I use the QR function built into ONEMenu, it fails to download the .vpk files it scans, instead giving a "Failed to download - ux0:downloads"  message in its place. I dont think its my camera because it works perfectly fine with VitaShell's QR function.

**Comment by ONElua** [comment]
please share your link to QR code

**Comment by ONElua** [comment]
Version?
In 3.65Enso works!!!

![2018-07-06-085731](https://user-images.githubusercontent.com/25811032/42382921-4ff4baf4-80fb-11e8-9c8e-0ea30ab40a6e.png)

![2018-07-06-085741](https://user-images.githubusercontent.com/25811032/42382928-567025da-80fb-11e8-9502-a2d72b183080.png)

**Comment by ONElua** [comment]
Do you hold X ???

**Comment by shinobuwu** [comment]
I completely forgot about this but as an example I will use vitaXash3d from rinnegatamante's vitadb site

http://vitadb.rinnegatamante.it/#/info/365

and I am on 3.65 Enso running 3.04 of ONEMenu

![2018-08-05-194442](https://user-images.githubusercontent.com/36655885/43691929-8ca84434-98e8-11e8-89c1-39aac79f6a7d.jpg)

**Comment by ONElua** [comment]
please try v3.06
