### ISSUE TITLE
Adding FTP support to ONEMenu?

### ISSUE THREAD

**Issue by shinobuwu** [ONElua/ONEMenu-for-PSVita#58]
I personally find ONEMenu's UI to be pleasing to the eyes in contrast to VitaShell, and I feel that adding FTP support would make it even better than it already is plus it will give people options instead of sticking with VitaShell.

**Comment by ONElua** [comment]
In the new versions, press select to go to the browser, then press triangle to open the contextual submenu, press L and R submenus changes

**Comment by ONElua** [comment]
![2018-08-06-090744](https://user-images.githubusercontent.com/25811032/43721799-75c77214-9959-11e8-944d-6118325179db.png)
