### ISSUE TITLE
[Bug] Incorrect display of LiveArea app names [In Rus]

### ISSUE THREAD

**Issue by XF10C** [ONElua/ONEMenu-for-PSVita#6]
![2017-11-14-210329](https://user-images.githubusercontent.com/30769120/32783840-ae5950c0-c97f-11e7-89a3-de12126bfa9d.png)

**Comment by ONElua** [comment]
Only in PS3 Remote Play  ??

**Comment by ONElua** [comment]
Please sendme show the param.sfo (NPXS10012)

**Comment by ONElua** [comment]
Please download only system.lua ("ux0:app/ONEMenu/system/)
https://github.com/ONElua/ONEMenu-for-PSVita/blob/master/ONEMenuVita/system/system.lua

**Comment by ONElua** [comment]
re-download vpk

**Comment by XF10C** [comment]
Fixed, Thx ;)
![2017-11-15-170714](https://user-images.githubusercontent.com/30769120/32830403-a5eb8220-ca27-11e7-8842-faaf0cf46d41.png)
