### ISSUE TITLE
udcd_uvc.skprx. is NOT 100%

### ISSUE THREAD

**Issue by GitHubyoyo** [ONElua/ONEMenu-for-PSVita#61]
I TSET.
After PSV opened, this project can not link usb.
It need to open Vitashell (tolink USB) at first, then this project can link too

**Comment by ONElua** [comment]
you have udcd_uvc.skprx v1.1 and onemenu v3.07 ??

**Comment by GitHubyoyo** [comment]
yeah ,I had both

**Comment by GitHubyoyo** [comment]
my device
PSV 2007, firmware 3.65 , and no enso

**Comment by ONElua** [comment]
Try:
https://www.dropbox.com/s/mmgcv33qtz5hyhx/ONEMenuVita.vpk?dl=0
remember : unsafe homebrew activated

**Comment by GitHubyoyo** [comment]
I will try,thanks

**Comment by GitHubyoyo** [comment]
The same.
After opening PSV and h-encore, It need to Running VitaShall's USB mode at first, oherwise onemenu's USB mode can not link normal.

**Comment by ONElua** [comment]
please try with onemenu v3.05
remember : unsafe homebrew activated
