### ISSUE TITLE
Error after shrinking of app

### ISSUE THREAD

**Issue by Rameron** [ONElua/ONEMenu-for-PSVita#68]
Hello!

Sometimes after shrinking of the application it don't wanna to start. Maybe instead of full removing of the files it will be a good idea to leave empty files with the same names? It works with Gravity Rush and *.psarc file.

**Comment by ONElua** [comment]
what is the game that gives you error??

**Comment by Rameron** [comment]
Gravity Rush and Uncharted (manual files). And in many games removing of the manual files cause error on start.

**Comment by ONElua** [comment]
I have tried and it works well...
You should only use it in Nonpdrm games
