### ISSUE TITLE
Icon art not loading

### ISSUE THREAD

**Issue by 4forksache** [ONElua/ONEMenu-for-PSVita#70]
I think I hit a limit for maximum number of icons that will show artwork.  Quite a lot of icons at the far right of the list/wheel? do not load the art.  I can scroll ahead and see the ones to the left loading, until it reaches a certain point then no more load. Is this a known limitation?  Can it be worked around by say adding folder support?

Using PSTV, v3.68, spoofed as 3.69 using h-encore.  SD2Vita (128 GB) as uma0, USB memory stick (256gb Sandisk ultra fit) as ux0.

List - No. Icons/bubbles - Artwork display status
PS VITA GAMES - 173 - All artwork
Homebrews - 18 - All artwork
Adreneline Bubbles - 201 - 136 with outwork, 65 without

I have added and removed various ps vita games and adrenaline bubbles.  It seems artwork can only be displayed for 327 icons.

**Comment by ONElua** [comment]
It is not limiting onemenu is the memory in the Vita, since they require a process to load and release images

**Comment by 4forksache** [comment]
Cool, understood.  Reckon there's away around this?
