### ISSUE TITLE
Move option not working, apps on uma0 not showing

### ISSUE THREAD

**Issue by Avrution** [ONElua/ONEMenu-for-PSVita#71]
Just installed this after seeing this is what App Manager Plus moved into (which still works perfect).

Selecting the move option does nothing - no menu or options.

Anything that was previously moved to uma0 doesn't show.

This is on 3.65

**Comment by ONElua** [comment]
I'm sorry, I'm off for the vita games.
Its only functional for homebrews.

**Comment by Avrution** [comment]
A shame, but thank you.  Back to the old app.
