### ISSUE TITLE
An error when installing the vpk with onemenu

### ISSUE THREAD

**Issue by yexun1995** [ONElua/ONEMenu-for-PSVita#74]
![2019-02-03-122453](https://user-images.githubusercontent.com/13676949/52172652-09e0d380-27af-11e9-8968-e309d43e0355.png)
On my PSV, the O button is accept and X button is cancel.
When I install a vpk file with onemenu,it displays like the screenshot above.It is very misleading.

**Comment by ONElua** [comment]
but install with O ??

**Comment by yexun1995** [comment]
> but install with O ??

Yes.When I click O button,it starts to install.

**Comment by ONElua** [comment]
please try
Install from Folder
Install vpk
Open official eboot.pbp
https://www.dropbox.com/s/mmgcv33qtz5hyhx/ONEMenuVita.vpk?dl=0

**Comment by yexun1995** [comment]
This version works nice.No errors have occurred so far.

![2019-02-03-143946](https://user-images.githubusercontent.com/13676949/52173699-220f1d80-27c4-11e9-80e2-a3f8314867e9.png)
![2019-02-03-144807](https://user-images.githubusercontent.com/13676949/52173700-26d3d180-27c4-11e9-982f-eda6bc2e340e.png)
![2019-02-03-144727](https://user-images.githubusercontent.com/13676949/52173701-29cec200-27c4-11e9-8fa7-7f4b04a37413.png)
![2019-02-03-145659](https://user-images.githubusercontent.com/13676949/52173702-2c311c00-27c4-11e9-910c-7c3c2ff5568e.png)

> please try
> Install from Folder
> Install vpk
> Open official eboot.pbp
> https://www.dropbox.com/s/mmgcv33qtz5hyhx/ONEMenuVita.vpk?dl=0
