### ISSUE TITLE
A little over 500 titles and half of them are not loaded

### ISSUE THREAD

**Issue by AZupa** [ONElua/ONEMenu-for-PSVita#80]
Hi, 

Just tried yesterday OneMenu on my pstv having a little over 500 titles. 
I was very exited when I've red that OneMenu can do this but unfortunately almost half of my games were not loaded with their thumbnails. 

Can someone support? 

Thanks!

**Comment by ONElua** [comment]
That is gpu related, the ps vita/tv has its own limits :(
