### ISSUE TITLE
Question: Own Categories for sorting Games

### ISSUE THREAD

**Issue by desolutionX** [ONElua/ONEMenu-for-PSVita#82]
Hi ONElua Team,

Thanks for your Work with Onemenu, works nice.

I`ve one Question about it:
Would it be possible to programm the opportunity of creating own Gamecategories for sorting the  Games, in example in Genres? So i can sort the Games on the vita my own way by choosing a Genre out of a List, wich creates a new categorie?

Thanks in Advance

**Comment by ONElua** [comment]
But it would only be one category for all your genres?

**Comment by desolutionX** [comment]
Hi, Thanks for respons.

I think in that way:
Maybe there is already a List of Genretypes implemented, if u press triangle and then the Left or Right Bumper there will be under "Sort Category" a next option "Genre Category" where u can assign each game to a Genres like:
- Games        ( already exists )
- Adrenalin,   ( already exists )
- Homebrew, ( already exists )
- Action,
- Adventure
- Beat`m up
- Hack`n Slay, 
- Platformer, 
- Racing
- RPG,
- Shooter, 
- Strategy
- Survivel Horror

In Main Menu u can now switch between these Categories/Genres  by pressing up or down. A Genre without a game will not show up.
