### ISSUE TITLE
Instant One Debugger after removing bubbles names

### ISSUE THREAD

**Issue by Lvieira21** [ONElua/ONEMenu-for-PSVita#83]
Hello!

I was browsing on reddit and found someone who removed bubble names, and I really loved it.
So I went on OneMenu and started removing the names of the bubbles, but after removing almost all names, OneMenu instantly went to debugger mode, and everytime I open it, it goes to that same page.
I think that the error i'm getting is: bad argument #3 to 'print' (string expected, got nil)

Is there a way to fix it?

**Comment by ONElua** [comment]
I need the complete error shown in the debugger
