### ISSUE TITLE
Unable to mount sd2vita using usb

### ISSUE THREAD

**Issue by ghost** [ONElua/ONEMenu-for-PSVita#84]
Hi,

Unfortunately I seem to be unable to connect  to my PC using the usb sd2vita option on the file explorer, causing an error every single time.

My sd2vita is my only storage and is set as the ux0 partition, I can mount it to my PC perfectly using vitashell and the sd2vita option there.

Is this an issue on my side? could there be a way for me to fix this?

Greetings and thanks for the program.

**Comment by ONElua** [comment]
do you install plugin for sd2vita???
Are you on the latest version of Onemenu? Also, whats the fw version of your PS Vita?

**Comment by ghost** [comment]
Hey there, I'm the guy who posted this issue before (had issues with my acc, I'm new here).

To answer your question: yes I installed the plugin, I am on the latest version of onemenu and my firmware is 3.65.

I highly doubt the problem is on me because vitashell's sd2vita connection is working 100%.
The option for connecting the official memory card is working though.

**Comment by ONElua** [comment]
in the explorer files
show uma0 ??

**Comment by ghost** [comment]
Yes, uma0 is the MCD and ux0 is sd2vita, mounting official card works. I also tried using only ux0 sd2vita WITHOUT uma0, it also doesn't mount sd2vita ux0.

Anything I should try out?

**Comment by ONElua** [comment]
please send me screenshot the error that shows you...
and screenshot of your file explorer (uma0)

**Comment by ghost** [comment]
Sure, here you go https://imgur.com/a/wDb8FpV

uma0 official memory card connection works, not ux0 sd2vita. Both work in vitashell.

**Comment by ONElua** [comment]
What is the button you press ?

**Comment by ghost** [comment]
Well, the sd2vita button. X, I think?
