### ISSUE TITLE
Custom Covers

### ISSUE THREAD

**Issue by EnigmaHall** [ONElua/ONEMenu-for-PSVita#9]
There´s a way to replace the game icons for another image inside OneMenu?
I don't mean mess with the game icon, but make the app look for another image based in the game folder name.
For example it founds a game in the directory NX00000EXP, then he search for NX00000EXP.npg in a covers directory and shows at the screen.
It could work for game covers instead the minimalist icons.
Maybe 3d covers in the future?

**Comment by ONElua** [comment]
icons of 128*128 ??

**Comment by EnigmaHall** [comment]
Yeap. There's a way to call a bigger image in the program? Excuse my bad english.

**Comment by ONElua** [comment]
The problem is the total number of images...
Could give you the option to load default icon or your customicon
GAMEID.PNG (128*128)

**Comment by EnigmaHall** [comment]
But vita haven't enogh memory to handle this? Or is a limitation of the lua?

**Comment by ONElua** [comment]
sorry for the GPU

**Comment by EnigmaHall** [comment]
My hope is if we will see something like wiiflow or freelaucher, with hability to see covers and back covers spinning on the screen.

**Comment by ONElua** [comment]
show me a example..please

**Comment by EnigmaHall** [comment]
https://m.youtube.com/watch?v=GbiP6V-IpGs

**Comment by EnigmaHall** [comment]
Sorry by the short answer I was in the work. But that's the question. Can one lua programation reach something close to wiiflow?

**Comment by szpieg-z-krainy-deszczowcow** [comment]
Would be great if this app not reading icons and bg but custom images. You said it's not enough memory, but You can swap images which going out of the screen. I'm not sure about delays in I/O from storages but it's worth a try. This could open way to a real nice cover flow menu style.

**Comment by EnigmaHall** [comment]
Thats my hope. And if a plugin can autostart Onemenu then it can become easily a future dash like freestyle.

**Comment by ONElua** [comment]
example for 50 pics... + icons + resources for theme
50 * 960 * 544 * 4 = 99.609375MB

**Comment by ONElua** [comment]
We need to do a load/free process every certain amount of images...

**Comment by EnigmaHall** [comment]
It dont need to be a full resolution img because vita has a small screen. But will work?

**Comment by ONElua** [comment]
but I really do not have enough time or the creativity to do it.. :(

**Comment by EnigmaHall** [comment]
You did a beautifull work so far. I dont have knowedge to do this. All I can do is give my thinking about what could be cool or point directions. I dont know if the wiiflow is open source, if is, maybe a look at the code could bring some light to solution. Or maybe you could mail someone from the team and ask for a guindace seen all are in the same direction.
