### ISSUE TITLE
ONEMenu crashes when scanning DLC and patches

### ISSUE THREAD

**Issue by Mitch1819** [ONElua/ONEMenu-for-PSVita#90]
Hi! First of all, I would like to thank you for this awesome app for the vita! However, it keeps crashing when I use the "RELOAD Content" feature. As a solution, I deleted any game that it crashed on. The problem is that once it finishes installing the main games, it proceeds to scan the DLC (addcont) and patch folders and then crashes every time, even after I fully deleted everything inside those folders (including the content of the "license/addcont" folder). Do you know why it does this and is there a solution?
Thanks in advance!

**Comment by ONElua** [comment]
Hi
Your DLC´s are encrypted?
With all the games ??

**Comment by ONElua** [comment]
FIX v3.19
