### ISSUE TITLE
Disappears when switching app

### ISSUE THREAD

**Issue by trintin94** [ONElua/ONEMenu-for-PSVita#92]
Whenever I minimise one menu, either by pressing the home button or opening another app, OneMenu disappears leaving a blank screen in the app switcher. I can't reopen it or close it, and clicking on the bubble just brings it to the blank screen again making it impossible to get back into one menu without completely restarting the Vita. 

![IMG_1749](https://user-images.githubusercontent.com/92192263/162087970-7c0bf8e3-73eb-4116-b10a-48ab81ed11b8.JPG)
As you can see on the top, OneMenu is selected in the app switcher but the screen is empty.

**Comment by DevDavisNunez** [comment]
Hello, 
it's strange, no one else has reported this bug, you can share more information, your console model, your firmware, your config.txt (plugin configuration), and how it happens, if you simply enter and want to exit or do something inside ONEmenu, the bug is presented.
