### ISSUE TITLE
Error when searching online for database themes

### ISSUE THREAD

**Issue by BinaryMessiah** [ONElua/ONEMenu-for-PSVita#94]
When searching for database themes online (Wifi is connected and working) I get "System Message: Error Get Database of Themes!" Rebooting the Vita and OneMenu doesn't help.

**Comment by ONElua** [comment]
Your version?
you have itls enso?

**Comment by TrueKintai** [comment]
My PS Vita also just crashes everytime i look for themes online and try to get past the purple theme

**Comment by ONElua** [comment]
@TrueKintai Do you have the folder ux0:data/ONEMENU?

**Comment by TrueKintai** [comment]
@ONElua Yes, i have ux0:data/ONEMENU/

**Comment by ONElua** [comment]
@TrueKintai
Try

https://www.dropbox.com/s/gixz9chfb0vq79m/ONEMenuVita.vpk?dl=0

**Comment by ONElua** [comment]
FIX v3.19
