### ISSUE TITLE
 Icons too big for Playstation Mobile

### ISSUE THREAD

**Issue by eHerbaciarz** [ONElua/ONEMenu-for-PSVita#96]
ONEMenu for PSVITA v3.18
Icons too big for Playstation Mobile - as in the attached picture:

![WhatsApp Image 2023-04-24 at 19 22 01](https://user-images.githubusercontent.com/10764145/234070939-9213ed44-6e5f-414d-8b79-2f604786ea23.jpeg)

**Comment by ONElua** [comment]
FIX v3.19
