### ISSUE TITLE
[Feature] Install PSP and PS1 Content

### ISSUE THREAD

**Issue by LakiBR** [ONElua/ONEMenu-for-PSVita#98]
Add PSP and PS1 games detection on Reload Content.

With Chovy-Sign its possible to resign the EBOOT.PBP, transfer to SD2Vita (faster than QCMA), and the games can be played. Using the NoPspEmuDrm it could install the EBOOT.PBP without resign.

Currently, triggering an "Update Database" install the bubbles (but it cost so much time).

**Comment by ONElua** [comment]
Try
https://www.dropbox.com/scl/fi/tvpncpxjoc5jisgkhg62l/ONEMenuVita.vpk?rlkey=bb6wrpnl2si8r2q3svoyp66m1&dl=0

**Comment by LakiBR** [comment]
Sorry for the late reply. It works only with NoPspEmuDrm plugin.

Without it, the game is not detected (and the bubble is installed without the plugin if the database is updated)

**Comment by ONElua** [comment]
https://github.com/ONElua/ONEMenu-for-PSVita/commit/926bda886cb25cf29299e2ffeea3b26bdcfd5a14
